### PR TITLE
fix: added fix for missing fs error

### PR DESCRIPTION
**Pull request by abhinav-from-contentstack**
- added fix for missing fs issue in web build
- updated version to 1.16.1

### CODE REVIEW

**Review by sunil-lakshman — COMMENTED** [review]
@abhinav-from-contentstack Please update the changelog file.

**Review by reeshika-h — APPROVED** [review]
Approved

**Comment by abhinav-from-contentstack** [comment]
done @sunil-lakshman

**Review by sunil-lakshman — APPROVED** [review]
Approved

**Review by nadeem-cs — APPROVED** [review]
Approved.

**Pull request merged**
